json.id comment.id
json.user_id comment.user_id
json.user comment.user.email
json.content comment.content
json.votes comment.votes
json.votecount comment.votes.count
json.score comment.score
json.user_image comment.user.user_image.url(:small)
json.created_at comment.created_at
json.formattedcreated_at comment.formattedcreated_at